name: Create GitHub Release

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: dawidd6/download-artifact@v2
        with:
          workflow: publish.yml
          name: app-publish

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./app-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
