name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Test
      run: |
        dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"
        
    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/test_results.trx'
